version: '3.8'
services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 30
      MEMORY: 10G
      MOTD: "BlockBuilders Cadw Dev server"
      DIFFICULTY: peaceful
      GENERATE_STRUCTURES: false
      SPAWN_ANIMALS: false
      SPAWN_MONSTERS: false
      SPAWN_NPCS: false
      SPAWN_PROTECTION: 0
      MODE: creative
      LEVEL_TYPE: FLAT
      EXISTING_OPS_FILE: SYNCHRONIZE
      OPS: |
        alex86465
        BlockB110
        Otto4903
        josephpalmercouk
      SPIGET_RESOURCES: 27448,19254
      PLUGINS: |
        https://dev.bukkit.org/projects/worldedit/files/latest
        https://ci.athion.net/job/FastAsyncWorldEdit/lastStableBuild/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.9.1-SNAPSHOT-661.jar
    ports:
      - "25565:25565"
    volumes:
      - ./server:/data
    restart: unless-stopped
volumes:
  mc-paper: {}